include naturalized citizen status when verifying ineligible_reasons
ideacrew/medicaid_gateway pull request #355
Opened 2023-07-31 16:56 UTC by jayreddy519

https://www.pivotaltracker.com/n/projects/2640060/stories/185369815

2023-08-01 15:44 UTC, saikumar9 requested changes
Please update the aca_entities latest sha once the aca_entities PR is merged.

2023-08-02 18:27 UTC, saikumar9 requested changes
@jayreddy519 Can you please add tests for this?

2023-08-02 18:27 UTC, saikumar9 commented on app/operations/eligibilities/aptc_csr/determine_other_eligibilities.rb
> +        reasons << 'total_ineligibility_no_lawful_presence' if applicant.valid_citizen_eligibility_check
👍

2023-08-03 18:58 UTC, saikumar9 approved these changes

2023-08-03 19:08 UTC, jacobkagon approved these changes

2023-08-03 19:08 UTC, merged