recording transfer failure
ideacrew/medicaid_gateway pull request #86
Opened 2021-11-17 17:19 UTC by nisanthyaganti9

2021-11-17 17:37 UTC, markgoho requested changes
@nisanthyaganti9 if there is no ticket to reference please add information to the PR:
1. who requested this change?
2. what impact does it have on the system?
3. how could it be QA'd?

2021-11-22 13:59 UTC, nisanthyaganti9 commented
> @nisanthyaganti9 if there is no ticket to reference please add information to the PR:
> 
> 1. who requested this change?
> 2. what impact does it have on the system?
> 3. how could it be QA'd?

Added a ticket & attached to PR.

2021-11-22 14:13 UTC, kristinmerbach approved these changes

2021-11-22 16:13 UTC, markgoho approved these changes

2021-11-22 16:13 UTC, merged